export const Endpoints = {
  Home: "/",
  Auth: "/login",
  AuthAdmin: "/admin",
  signup: "/signup",
  users: "/users",
  products: "/products",
  Contact: "/Contact",
  productId: "/products/:id",
  productForm: "/productform",
  messages: "/messages",
  checkout: "/checkout",
  profile: "/profile",
  payment: "/payment",
  orderSuccess: "/order-success",
};
